# Generated by Django 5.1 on 2024-08-15 23:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PastoralVisitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('state', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tb_pastoral_visitor',
                'ordering': ['name'],
            },
        ),
    ]
