# Generated by Django 5.1 on 2024-08-12 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PastoralGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 8, 12, 17, 14, 0, 536432, tzinfo=datetime.timezone.utc))),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(blank=True, default='NA', max_length=10, null=True)),
                ('description', models.CharField(blank=True, default='NA', max_length=2000, null=True)),
                ('logo', models.CharField(default='NA', max_length=50)),
                ('url', models.CharField(default='NA', max_length=50)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('foundation_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tb_pastoral_group',
                'ordering': ['name'],
            },
        ),
    ]
