# Generated by Django 5.1 on 2024-08-15 10:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pastoral_member_api', '0004_alter_pastoralmember_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastoralCoordination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('status', models.BooleanField(default=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('profile_id', models.IntegerField()),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('renewal_date', models.DateTimeField(blank=True, null=True)),
                ('pastoral_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastoral_member_api.pastoralmember')),
            ],
            options={
                'db_table': 'tb_pastoral_coordination',
            },
        ),
    ]
