# Generated by Django 5.1 on 2024-08-11 19:26

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution_api', '0003_alter_institution_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 8, 11, 19, 26, 51, 431396, tzinfo=datetime.timezone.utc))),
                ('nif', models.CharField(max_length=20)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution_api.institution')),
            ],
            options={
                'db_table': 'tb_provider',
                'ordering': ['-created_date'],
            },
        ),
    ]
