# Generated by Django 5.1 on 2024-08-10 21:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tb_type_institution',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 8, 10, 21, 10, 22, 201068, tzinfo=datetime.timezone.utc))),
                ('name', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('street', models.CharField(blank=True, max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=10, null=True)),
                ('state', models.BooleanField(default=True)),
                ('updated_date', models.DateTimeField(null=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address_api.country')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address_api.county')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution_api.typeinstitution')),
            ],
            options={
                'db_table': 'tb_institution',
                'ordering': ['name'],
            },
        ),
    ]
