# Generated by Django 5.1 on 2024-08-11 19:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institution_api', '0002_alter_institution_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='created_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 8, 11, 19, 26, 51, 429487, tzinfo=datetime.timezone.utc)),
        ),
    ]
