# Generated by Django 5.1 on 2024-08-13 22:02

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pastoral_group_api', '0002_alter_pastoralgroup_created_date'),
        ('pastoral_member_api', '0002_alter_pastoralmember_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastoralMemberHasGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 8, 13, 22, 2, 47, 848072, tzinfo=datetime.timezone.utc))),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('pastoral_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastoral_group_api.pastoralgroup')),
                ('pastoral_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastoral_member_api.pastoralmember')),
            ],
            options={
                'db_table': 'tb_pastoral_member_has_group',
            },
        ),
    ]
