# Generated by Django 5.1 on 2024-08-15 22:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pastoral_activity_api', '0002_alter_pastoralactivity_options'),
        ('pastoral_coordination_api', '0001_initial'),
        ('pastoral_member_api', '0005_alter_pastoralmember_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastoralActivityMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('cancellation_date', models.DateTimeField(blank=True, null=True)),
                ('status_activity', models.CharField(default='C', max_length=1)),
                ('pastoral_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pastoral_activity_api.pastoralactivity')),
                ('pastoral_coordination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pastoral_coordination_api.pastoralcoordination')),
                ('pastoral_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pastoral_member_api.pastoralmember')),
            ],
            options={
                'db_table': 'tb_pastoral_activity_member',
            },
        ),
    ]
