# Generated by Django 5.1 on 2024-08-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastoral_activity_member_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastoralactivitymember',
            name='payment',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='pastoralactivitymember',
            name='status_activity',
            field=models.CharField(default='P', max_length=2),
        ),
    ]
