# Generated by Django 5.1 on 2024-08-15 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastoral_activity_member_api', '0002_pastoralactivitymember_payment_and_more'),
        ('pastoral_visitor_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastoralactivitymember',
            name='pastoral_visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pastoral_visitor_api.pastoralvisitor'),
        ),
    ]
