# Generated by Django 5.1 on 2024-08-15 16:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastoralActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('state', models.BooleanField(default=True)),
                ('type_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_api.typeactivity')),
            ],
            options={
                'db_table': 'tb_pastoral_activity',
            },
        ),
    ]
