# Generated by Django 5.1 on 2024-08-15 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastoral_activity_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastoralactivity',
            options={'ordering': ['name']},
        ),
    ]
