# Generated by Django 5.1 on 2024-08-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastoral_activity_api', '0002_alter_pastoralactivity_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pastoralactivity',
            name='state',
        ),
        migrations.AddField(
            model_name='pastoralactivity',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pastoralactivity',
            name='publication_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pastoralactivity',
            name='status',
            field=models.CharField(default='C', max_length=2),
        ),
    ]
