# Generated by Django 5.1 on 2024-08-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastoral_activity_api', '0003_remove_pastoralactivity_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastoralactivity',
            name='suspended_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
