# Generated by Django 5.1 on 2024-08-11 20:45

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address_api', '0001_initial'),
        ('general_api', '0001_initial'),
        ('religion_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastoralMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 8, 11, 20, 45, 42, 343524, tzinfo=datetime.timezone.utc))),
                ('first_name', models.CharField(db_index=True, max_length=30)),
                ('last_name', models.CharField(db_index=True, max_length=50)),
                ('photo', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('civil_state', models.CharField(default='S', max_length=1)),
                ('state', models.BooleanField(default=False)),
                ('street', models.CharField(blank=True, max_length=30, null=True)),
                ('house_number', models.CharField(blank=True, max_length=10, null=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('academic_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general_api.academiclevel')),
                ('county', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address_api.county')),
                ('nacionality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address_api.country')),
                ('religion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='religion_api.religion')),
                ('sacrament', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='religion_api.sacrament')),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general_api.school')),
                ('university', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general_api.university')),
            ],
            options={
                'db_table': 'tb_pastoral_member',
                'ordering': ('last_name', 'first_name'),
            },
        ),
    ]
