# Generated by Django 5.1 on 2024-08-15 10:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastoral_member_api', '0002_alter_pastoralmember_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastoralmember',
            name='created_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 8, 15, 10, 13, 8, 357660, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='pastoralmember',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
