# Generated by Django 5.1 on 2024-08-15 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastoral_member_api', '0003_alter_pastoralmember_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastoralmember',
            name='created_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 8, 15, 10, 21, 51, 337053, tzinfo=datetime.timezone.utc)),
        ),
    ]
