# Generated by Django 5.1 on 2024-08-15 22:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastoral_member_api', '0004_alter_pastoralmember_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastoralmember',
            name='created_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 8, 15, 22, 12, 6, 738703, tzinfo=datetime.timezone.utc)),
        ),
    ]
