# Generated by Django 5.1 on 2024-08-17 08:50

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pastoral_activity_api', '0002_alter_pastoralactivity_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 8, 17, 8, 50, 15, 672092, tzinfo=datetime.timezone.utc))),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.BooleanField(default=True)),
                ('photo', models.CharField(max_length=100)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('pastoral_activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pastoral_activity_api.pastoralactivity')),
            ],
            options={
                'db_table': 'tb_publication',
                'ordering': ['title'],
            },
        ),
    ]
