# Generated by Django 5.1 on 2024-08-17 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='photo',
        ),
        migrations.AddField(
            model_name='publication',
            name='path_photo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='created_date',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 8, 17, 8, 53, 32, 737526, tzinfo=datetime.timezone.utc)),
        ),
    ]
