# .github/workflows/python-tests.yml

name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python 3.11
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests with pytest
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q

      # Optional: Upload test results or other artifacts
      # - name: Upload test results
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: pytest-results
      #     path: test-results
