# Generated by Django 5.1 on 2024-08-10 21:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institution_api', '0002_alter_institution_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_created=True, default=datetime.datetime(2024, 8, 10, 21, 40, 49, 361716, tzinfo=datetime.timezone.utc))),
                ('description', models.CharField(default='NA', max_length=500)),
                ('state', models.BooleanField(default=True)),
                ('updated_date', models.DateTimeField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institution_api.institution')),
            ],
            options={
                'db_table': 'tb_agreement',
            },
        ),
    ]
